using CompetingClocks
using Documenter
using Literate
using Random
using Distributions


rebuild_literate = "--fresh" in ARGS
make_pdf = "--pdf" in ARGS
# `make_pdf` may require latex and font support.
# sudo apt install latexmk texlive-luatex texlive-fonts-extra fonts-lmodern
# sudo luaotfload-tool --update

# Literate puts images into png files in the same directory as the source
# but we would like them in the assets subdirectory instead, so here we
# postprocess the markdown generated by Literate to tell it where to look.
function postprocess_markdown(sfile::String)
    replace(sfile, r"\(([a-z0-9_\-]+\.(png|pdf|svg))\)" => s"(literate/\1)")
end


example_base = joinpath(dirname(@__FILE__), "src")
adliterate = [
    ("simple_board.jl", "mainloop"),
    ("distributions.jl", "distributions"),
    ("constant_birth.jl", "constant_birth"),
    ("sir.jl", "sir"),
    ("commonrandom.jl", "commonrandom"),
    ("reliability.jl", "reliability"),
    ("memory.jl", "memory"),
    ("gsmp.jl", "gsmp"),
    ("hierarchical.jl", "hierarchical"),
    ("gene_expression.jl", "gene_expression")
]
literate_subdir = joinpath(example_base, "literate")
isdir(literate_subdir) || mkdir(literate_subdir)

if rebuild_literate
    for rmchunk in readdir(literate_subdir; join=true)
        rm(rmchunk)
    end
end

for (source, target) in adliterate
    fsource, ftarget = joinpath.(example_base, [source, target])
    if rebuild_literate
        rm("$(ftarget).md", force=true)
    end
    if !isfile("$(ftarget).md") || mtime(fsource) > mtime("$(ftarget).md")
        @info "Literate of $source to $target"
        Literate.markdown(
            fsource,
            example_base,
            name=target,
            postprocess=postprocess_markdown,
            execute=true
        )
        ischunk = Regex("$(target)-[0-9]+.(png|svg|pdf)")
        chunks = [fn for fn in readdir(example_base) if match(ischunk, fn) !== nothing]
        for chunk in chunks
            chunk_source = joinpath(example_base, chunk)
            chunk_target = joinpath(example_base, "literate", chunk)
            @info "Moving $chunk_source to $chunk_target"
            mv(chunk_source, chunk_target; force=true)
        end
    end
end

if make_pdf
    format = Documenter.LaTeX()
else
    format = Documenter.HTML(;
        prettyurls=get(ENV, "CI", nothing) == "true",
        edit_link="main",
        size_threshold_warn=2^17,
        size_threshold=2^18,
        canonical="https://adolgert.github.io/CompetingClocks.jl",
        assets=String[],
    )
end

makedocs(;
    modules=[CompetingClocks],
    authors="Andrew Dolgert <adolgert@uw.edu>",
    sitename="CompetingClocks.jl Documentation",
    checkdocs=:none,  # Don't require all internal methods to be documented
    format=format,
    pages=[
        "Home" => "index.md",
        "Getting Started" => [
            "install.md",
            "quickstart.md",
            "mainloop.md",
            "choosing_sampler.md",
        ],
        "User Guide" => [
            "integration-guide.md",
            "low_level_interface.md",
            "samplers.md",
            "guide.md",
            "distributions.md",
            "hierarchical.md",
            "debugging.md",
        ],
        "Examples" => [
            "Reliability" => "reliability.md",
            "SIR Model" => "sir.md",
            "Birth-death Process" => "constant_birth.md",
            "memory.md",
            "Gene Expression" => "gene_expression.md",
        ],
        "Statistical Methods" => [
            "commonrandom.md",
            "importance_skills.md",
            "hamiltonianmontecarlo.md",
            "Gen.jl Integration" => [
                "gen/overview.md",
                "gen/distribution.md",
                "gen/generative_function.md",
                "gen/observation_likelihood.md",
                "gen/importance_mixture.md",
                "gen/hmc_paths.md",
            ],
            "gen/turing_dist.md",
            "gen/survival_snippet.md",
        ],
        "API Reference" => [
            "contextinterface.md",
            "reference.md",
            "algorithms.md",
        ],
    ],
)

deploydocs(;
    target="build",
    repo="github.com/adolgert/CompetingClocks.jl.git",
    devbranch="main",
    branch="gh-pages"
)
